/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.27
 * Generated at: 2019-05-01 18:29:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class date_005fselection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheet.css\"/>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script> <!--src for Jquery -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/air-datepicker-master/dist/js/datepicker.min.js\"> </script> <!--src for calendar -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/air-datepicker-master/dist/js/i18n/datepicker.en.js\"> </script> <!--src for calendar -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/air-datepicker-master/dist/css/datepicker.min.css\" rel=\"stylesheet\"/> <!--CSS specifically for calendar -->    \r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\"> <!-- font for the search button -->\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    /*Styling for the blue search button*/\r\n");
      out.write("    * \r\n");
      out.write("    {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    /* Style for the search field */\r\n");
      out.write("    #datePicker\r\n");
      out.write("    {\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("        border: 1px solid grey;\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        background: #f1f1f1;\r\n");
      out.write("    }\r\n");
      out.write("    /* Style for the submit button */\r\n");
      out.write("    .submit_Button\r\n");
      out.write("    {\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 5%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background: #2196F3;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("        border: 1px solid grey;\r\n");
      out.write("        border-left: none; /* Prevent double borders */\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .buttons\r\n");
      out.write("    {\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        background: white;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("        border: 2px solid #2196F3;\r\n");
      out.write("        border-bottom: 4px solid #2196F3;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .buttons:hover\r\n");
      out.write("    {\r\n");
      out.write("        border: 2px solid #0b7dda;\r\n");
      out.write("        border-bottom: 4px solid #0b7dda;\r\n");
      out.write("        background: yellow;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    th\r\n");
      out.write("    {\r\n");
      out.write("    \talign: left;\r\n");
      out.write("    \tfont-size: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /*Style for the search button hover */\r\n");
      out.write("    #submit_Button:hover    \r\n");
      out.write("    {\r\n");
      out.write("        background: #0b7dda;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .hidden\r\n");
      out.write("    {\r\n");
      out.write("    \tvisibility: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .visible\r\n");
      out.write("    {\r\n");
      out.write("    \tvisibility: visible;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    var submit_btn;\r\n");
      out.write("    var date_container;\r\n");
      out.write("    var div;\r\n");
      out.write("    var submit_form;\r\n");
      out.write("    var date_holder;\r\n");
      out.write("    var time_holder;\r\n");
      out.write("    var weekday_times = new Array(\"9:00 AM\",\"10:00 AM\" ,\"11:00 AM\", \"12:00 PM\", \"1:00 PM\",\"2:00 PM\",\"3:00 PM\");\r\n");
      out.write("    var weekend_times = new Array(\"10:00 AM\" ,\"11:00 AM\");\r\n");
      out.write("    var table_string = \" \";\r\n");
      out.write("    var days_of_the_week = new Array(\"Sunday\", \"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\");\r\n");
      out.write("    var user_date, user_date1, user_date2;\r\n");
      out.write("    var parts; \r\n");
      out.write("    var day, month, year;\r\n");
      out.write("    \r\n");
      out.write("    function start(){\r\n");
      out.write("    \t\r\n");
      out.write("    \tdiv = document.getElementById(\"database_results\");\r\n");
      out.write("        submit_btn = document.getElementById(\"submit_Button\");\r\n");
      out.write("        submit_btn.addEventListener(\"click\", function(){ dateEntered(); });\r\n");
      out.write("        submit_form = document.getElementById(\"submit_form\");\r\n");
      out.write("        date_holder = document.getElementById(\"date_holder\");\r\n");
      out.write("        time_holder = document.getElementById(\"time_holder\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function dateEntered(){\r\n");
      out.write("    \ttable_string = \" \";\r\n");
      out.write("    \tdate_container = document.getElementById(\"datePicker\"); //Value is MM/DD/YYYY\r\n");
      out.write("    \tparts = date_container.value.split('/');\r\n");
      out.write("    \tday = parseInt(parts[1]);\t//DD\r\n");
      out.write("    \tmonth = parseInt(parts[0]); //MM\r\n");
      out.write("    \tyear = parseInt(parts[2]);\t//YYYY\r\n");
      out.write("    \tuser_date0 = new Date(year, month - 1, day);\r\n");
      out.write("    \tuser_date1 = new Date(year, month - 1, day + 1);\r\n");
      out.write("    \tuser_date2 = new Date(year, month - 1, day + 2);\r\n");
      out.write("    \ttable_string += \"<table>\"\r\n");
      out.write("    \t\ttable_string += \"<tr>\"\r\n");
      out.write("    \t\t\ttable_string += \"<th align='left' colspan='4'>\" + user_date0.toDateString() + \"</th>\";\r\n");
      out.write("    \t\ttable_string += \"</tr>\";\r\n");
      out.write("    \t\ttable_string += \"<tr>\";\r\n");
      out.write("    \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(1, '9:00 AM')'>9:00 AM</button></td>\";\r\n");
      out.write("    \t\t\ttable_string += \"<td><button  type='button' class='buttons' onclick='timeSelected(1, '10:00 AM')'>10:00 AM</button></td>\";\r\n");
      out.write("    \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(1, '11:00 AM')'>11:00 AM</button></td>\";\r\n");
      out.write("    \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(1, '12:00 PM')'>12:00 PM</button></td>\";\r\n");
      out.write("    \t\ttable_string += \"</tr>\";\r\n");
      out.write("        \ttable_string += \"<tr>\";\r\n");
      out.write("    \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(1, '1:00 PM')'>1:00 PM</button></td>\";\r\n");
      out.write("    \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(1, '2:00 PM')'>2:00 PM</button></td>\";\r\n");
      out.write("    \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(1, '3:00 PM')'>3:00 PM</button></td>\";\r\n");
      out.write("    \t\ttable_string += \"</tr>\";    \t\t\t\r\n");
      out.write("    \ttable_string += \"</table>\"\r\n");
      out.write("    \t\ttable_string += \"<br/>\"\r\n");
      out.write("        table_string += \"<table>\"\r\n");
      out.write("        \ttable_string += \"<tr>\"\r\n");
      out.write("       \t\t\ttable_string += \"<th align='left' colspan='4'>\" + user_date1.toDateString() + \"</th>\";\r\n");
      out.write("       \t\ttable_string += \"</tr>\";\r\n");
      out.write("       \t\ttable_string += \"<tr>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(2, '9:00 AM')'>9:00 AM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button  type='button' class='buttons' onclick='timeSelected(2, '10:00 AM')'>10:00 AM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(2, '11:00 AM')'>11:00 AM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(2, '12:00 PM')'>12:00 PM</button></td>\";\r\n");
      out.write("       \t\ttable_string += \"</tr>\";\r\n");
      out.write("           \ttable_string += \"<tr>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(2, '1:00 PM')'>1:00 PM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(2, '2:00 PM')'>2:00 PM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(2, '3:00 PM')'>3:00 PM</button></td>\";\r\n");
      out.write("       \t\ttable_string += \"</tr>\";    \t\t\t\r\n");
      out.write("       \ttable_string += \"</table>\"\r\n");
      out.write("       \t\ttable_string += \"<br/>\"\r\n");
      out.write("       \ttable_string += \"<table>\"\r\n");
      out.write("       \t\ttable_string += \"<tr>\"\r\n");
      out.write("       \t\t\ttable_string += \"<th align='left' colspan='4'>\" + user_date2.toDateString() + \"</th>\";\r\n");
      out.write("       \t\ttable_string += \"</tr>\";\r\n");
      out.write("       \t\ttable_string += \"<tr>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(3, '9:00 AM')'>9:00 AM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button  type='button' class='buttons' onclick='timeSelected(3, '10:00 AM')'>10:00 AM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(3, '11:00 AM')'>11:00 AM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(3, '12:00 PM')'>12:00 PM</button></td>\";\r\n");
      out.write("       \t\ttable_string += \"</tr>\";\r\n");
      out.write("           \ttable_string += \"<tr>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(3, '1:00 PM')'>1:00 PM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(3, '2:00 PM')'>2:00 PM</button></td>\";\r\n");
      out.write("       \t\t\ttable_string += \"<td><button type='button' class='buttons' onclick='timeSelected(3, '3:00 PM')'>3:00 PM</button></td>\";\r\n");
      out.write("       \t\ttable_string += \"</tr>\";    \t\t\t\r\n");
      out.write("       \ttable_string += \"</table>\";\r\n");
      out.write("       \ttable_string += \"<br/>\";    \t\r\n");
      out.write("\r\n");
      out.write("    \tdiv.innerHTML = table_string;\r\n");
      out.write("       \t\r\n");
      out.write("       \tsubmit_form.classList.remove(\"hidden\");\r\n");
      out.write("       \tsubmit_form.classList.add(\"visible\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function timeSelected(date, time){\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(date == 0){\r\n");
      out.write("    \t\tdate_holder.value = user_date0;\r\n");
      out.write("    \t}else if(date == 1){\r\n");
      out.write("    \t\tdate_holder.value = user_date1;\r\n");
      out.write("    \t}else if(date == 2){\r\n");
      out.write("\t\t\tdate_holder.value = user_date2;\r\n");
      out.write("\t\t}\r\n");
      out.write("    \t\r\n");
      out.write("    \ttime_holder.value = time; \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    window.addEventListener('load', start, false);\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<title>Appointment Date Selection</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <h1>Let's find a time that works for you.</h1>\r\n");
      out.write("    <br>\r\n");
      out.write("    <input id='datePicker' type='text' class='datepicker-here' data-language='en' name=\"date\" value=\"CHOOSE DATE\"/> <!--class for date picker must be \"datepicker-here\" -->\r\n");
      out.write("    <button type=\"button\" id=\"submit_Button\" class=\"submit_Button\"><i class=\"fa fa-search\" ></i></button> <!--https://www.w3schools.com/howto/howto_css_search_button.asp -->\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"database_results\">\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("    </div>\r\n");
      out.write("    <form class=\"hidden\" id=\"submit_form\" action=\"/spring/date_selected\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"date_holder\" name=\"appointmentdate\" value=\"asd\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"time_holder\"name=\"appointmentstartTime\" value=\" \">\r\n");
      out.write("\t<button type=\"submit\" class=\"submit_Button\">Continue</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
